### ISSUE TITLE
We can't lay on the same beds who are opposed. 

### ISSUE THREAD

**Issue by Havasiz** [TerbSEC/ChairBedSystem#4]
We can't lay on the same beds who are opposed. Like in the GABZ Hospital.

**Comment by TerbSEC** [comment]
Can you take a Screenshot? This code is made for that only one person can lay on a bed or sit on a chair at the time.

**Comment by Havasiz** [comment]
Oh actually i've fixed it somehow or i was doing it wrong. Btw thanks ;)
