### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Luis26x** [TerbSEC/ChairBedSystem#5]
![Capture](https://user-images.githubusercontent.com/60543200/78458226-bc474b80-767d-11ea-8939-24419a603fbe.PNG)
![Capture1](https://user-images.githubusercontent.com/60543200/78458227-bcdfe200-767d-11ea-9583-80b4c2412ee3.PNG)

**Comment by TerbSEC** [comment]
I've recoded nearly the hole code.. Can you tell me how it works with the newest version? Thanks.
